Import('master_env')

env = master_env.Clone()

env.PiPythonPackage(package='Technobear', per_agent='plg_oscpad')
env.PiAgent('osc_pad', 'plg_oscpad','osc_pad_plg', cversion='0.0.10')
if env['IS_MACOSX']:
    env.PiEtc('Technobear',Split('postflight-oscpad'))
