Import('master_env')

env = master_env.Clone()

env.PiPythonPackage(package='Technobear', per_agent='plg_midi_monitor')
env.PiAgent('midi_monitor', 'plg_midi_monitor','midi_monitor_plg', cversion='0.0.4', lexicon='lexicon.txt')
if env['IS_MACOSX']:
    env.PiEtc('Technobear',Split('postflight-midi_monitor'))
