#!/bin/sh
su $USER -c "ln -s $PI_PREFIX/resources ~/Desktop/README"
su $USER -c "cp $PI_PREFIX/resources/Scripts/*.bc ~/Library/Eigenlabs/Scripts/" 
su $USER -c "cp $PI_PREFIX/bin/libpiop.dylib $PI_LIBPATH" 
